// A command name has to agree in four places at once, and only one of them is compiled:
// the page's call(), generate_handler! in main.rs, the COMMANDS list build.rs turns into
// permissions, and the capability that grants them. Miss the last two and every call is
// refused at runtime with "not allowed" — which is what an empty window looks like.

import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const assets = join(here, "..", "ui", "assets");
const tauri = join(here, "..", "src-tauri");

const sorted = (values) => [...new Set(values)].sort();

/// Every command the page asks for, including the one the action helper wraps.
function calledByThePage() {
  const names = [];
  for (const file of readdirSync(assets).filter((name) => name.endsWith(".js"))) {
    const source = readFileSync(join(assets, file), "utf8");
    for (const match of source.matchAll(/\bcall\(\s*"([a-z_]+)"/g)) names.push(match[1]);
    // `act(...)` is the one indirection: it always reaches worktree_action.
    if (/\bact\(/.test(source)) names.push("worktree_action");
  }
  return sorted(names);
}

function registeredInMain() {
  const source = readFileSync(join(tauri, "src", "main.rs"), "utf8");
  const block = /generate_handler!\[([\s\S]*?)\]/.exec(source);
  assert.ok(block, "main.rs must register its commands with generate_handler!");
  return sorted(
    block[1]
      .split(",")
      .map((entry) => entry.trim().replace(/^commands::/, ""))
      .filter(Boolean),
  );
}

function declaredInBuild() {
  const source = readFileSync(join(tauri, "build.rs"), "utf8");
  const block = /COMMANDS: &\[&str\] = &\[([\s\S]*?)\];/.exec(source);
  assert.ok(block, "build.rs must declare COMMANDS so tauri-build generates the permissions");
  return sorted([...block[1].matchAll(/"([a-z_]+)"/g)].map((match) => match[1]));
}

function grantedByTheCapability() {
  const capability = JSON.parse(readFileSync(join(tauri, "capabilities", "default.json"), "utf8"));
  return sorted(
    capability.permissions
      .filter((name) => name.startsWith("allow-"))
      .map((name) => name.slice("allow-".length).replaceAll("-", "_")),
  );
}

test("every command the page calls is registered in main.rs", () => {
  const missing = calledByThePage().filter((name) => !registeredInMain().includes(name));
  assert.deepEqual(missing, [], "the page calls commands generate_handler! does not register");
});

test("every registered command is declared in build.rs", () => {
  assert.deepEqual(registeredInMain(), declaredInBuild(),
    "a command missing from COMMANDS gets no permission, and the ACL refuses it at runtime");
});

test("every declared command is granted by the capability", () => {
  assert.deepEqual(declaredInBuild(), grantedByTheCapability(),
    "a command with no allow- entry is refused even though it exists");
});

test("tauri-build has generated a permission file for each command", () => {
  const generated = sorted(
    readdirSync(join(tauri, "permissions", "autogenerated"))
      .filter((name) => name.endsWith(".toml"))
      .map((name) => name.replace(/\.toml$/, "")),
  );
  assert.deepEqual(generated, declaredInBuild());
});

test("the page no longer speaks HTTP", () => {
  for (const file of readdirSync(assets).filter((name) => name.endsWith(".js"))) {
    const source = readFileSync(join(assets, file), "utf8");
    assert.ok(!/\bfetch\(\s*["'`]/.test(source), `${file} still calls fetch()`);
    assert.ok(!source.includes("/api/"), `${file} still names an HTTP route`);
  }
});
